### ISSUE TITLE
Parsing Issues when using KJV modules

### ISSUE THREAD

**Issue by clyde100** [alphapapa/sword-to-org#2]
When using KJV modules, verses are being "missed".  This is caused by how diatheke outputs verses that contain pilcrow symbols in the OSIS milestone element.  This is not an issue that occurs when using ESV modules, so probably was not experienced during testing.

Executing "diatheke -b KJV -k John 1:1-8" in a terminal window will show the John 1:6 reference on one line and its text on the following line.  This verse has a pilcrow symbol.  Executing (sword-to-org-insert-outline "KJV" "John 1:1-8") in an org-mode buffer will result in John 1:6 "missing" in the generated output.  It is actually appended to the end of John 1:5's text.

Calling diatheke as follows: diatheke -b KJV -f OSIS -k John 1:1-8 | perl -pe 's/<.*?>//'
will result in every verse being available with the same output format.

I have added "-f OSIS" to the call-process sexps and proven that all the verses appear as expected in the org-mode buffer (albeit with all the OSIS related markup).  I don't have the elisp chops needed to properly add something, as suggested via my google-fu, like: (while (re-search-forward "<.*?>" nil t) (replace-match "")) in the right location.

I did a quick search through the diatheke source code, but couldn't locate the code causing the pilcrow related issue to begin with, so I think for now this is the best solution.

Thank you for your initial work on this module.

**Comment by alphapapa** [comment]
Hi there,

Thanks very much for reporting this.  I didn't think anyone was even using this code.  I didn't test it with any other modules IIRC, so it doesn't surprise me that there are a few bugs.  I hope to someday parse the sword files directly (not necessarily in elisp), which would solve a lot of issues like this.  (It would also help a lot if Diatheke had a simple structured output mode, like JSON...)

I made some changes that seem to fix this passage for the KJV, but I haven't tested it on other passages or modules.  Would you mind giving it a more thorough test and let me know if it works for you?  If so, I'll merge it to master.

**Comment by clyde100** [comment]
This seems to have fixed my immediate issue.  Thank you for your very quick fix!

I have been playing around with this package for a few months.  The first thing I used this package for is to generate a "verse of the day" org-mode file that I converted to an ics file and I upload via a python simple http server to my iOS calendar:

```#+NAME: ScriptureReference
#+BEGIN_SRC emacs-lisp :var ref="Gen 1:1" :exports none
  ;; Since KJV is the only module currently installed,
  ;; will HARDCODE this value
  (sword-to-org--diatheke-get-text "KJV" ref)
#+END_SRC

* 2018
** January
*** Today's Scripture
SCHEDULED: <2018-01-01 Mon>
#+CALL: ScriptureReference(ref="Jeremiah 32:17")
<<< ETC. for a few months >>>
```
Then I thought, why not use this as a direct quoting mechanism into the org-mode files I use to generate my LaTeX based PDF Bible Study handouts.  So I hacked together the following by judicious use of cut-n-paste (you might recognize some of the code!):
```#+NAME: ScriptureReference
#+BEGIN_SRC emacs-lisp :var ref="Mat 1:1" :exports none
    ;; Since KJV is the only module currently installed,
    ;; will HARDCODE this value
  (with-temp-buffer
    (cl-loop for passage in (sword-to-org--diatheke-parse-text (sword-to-org--diatheke-get-text "KJV" ref))
	     do (-let (((&plist :book book :chapter chapter :verse verse :text text) passage))
		  (insert (format "%s\n" text))
		  ))
    (buffer-substring (point-min) (save-excursion
				    (goto-char (point-max))
				    (forward-line -2)
				    (end-of-line)
				    (point))))
#+END_SRC
* Genealogy of Jesus
The Bible records two different genealogies of Jesus.  The first one is found in Matthew chapter 1
#+CALL: ScriptureReference(ref="Mat 1:1-18")
and the second is found in Luke, chapter 3, beginning in with verse 23
#+CALL: ScriptureReference(ref="Luke 3:23-39")
```
I'm still not 100% satisfied right now with how all of this is working.  It would be nice to have the scripture reference at the end of the quote, so it looks similar to what is typically published in books.  That is a task for another time right now.

I am not an elisp'er by any stretch of the imagination, but I have amazed friends and family with all the things I am able to do with emacs, org-mode, LaTeX, and a little patience.  Who needs an Office Suite?

**Comment by alphapapa** [comment]
Wow, thanks for those awesome examples!  It had never occurred to me to use Org source blocks to insert scripture references and passages!  I wonder if we could make it even easier by using Org macros, so you could do something like `{{{ref "Luke 3:23-39"}}}`.  I'll have to look into that; I haven't actually used Org macros before.

I can add the scripture reference to your example easily, standby...  :)

**Comment by alphapapa** [comment]
Ok, I think this should work pretty well!   I just pushed a commit that adds a function and command to make this easier.  Now you can use this code in Org:
```org
#+MACRO: refPara #+CALL: Diatheke(ref=$1, paragraph="t")
#+MACRO: refLines #+CALL: Diatheke(ref=$1, paragraph="")

#+NAME: Diatheke
#+BEGIN_SRC emacs-lisp :var ref="" paragraph="" :exports results :results raw
  (concat "#+BEGIN_QUOTE" "\n"
          (sword-to-org--passage ref :paragraph (s-present? paragraph))
          (when (s-present? paragraph)
            (concat "  (" ref ")")) "\n" 
          "#+END_QUOTE" "\n")
#+END_SRC

* Genealogy of Jesus
The Bible records two different genealogies of Jesus.  The first one is found in Matthew chapter 1:

{{{refLines("Mat 1:1-2")}}}

and the second is found in Luke, chapter 3, beginning in with verse 23:

{{{refPara("Luke 3:23-24")}}}
```
And you get output like this when exporting:
```
The Bible records two different genealogies of Jesus.  The first one is
found in Matthew chapter 1:

      Matthew 1:1 The book of the genealogy of Jesus Christ, the
      son of David, the son of Abraham.

      Matthew 1:2 Abraham was the father of Isaac, and Isaac the
      father of Jacob, and Jacob the father of Judah and his
      brothers,

and the second is found in Luke, chapter 3, beginning in with verse 23:

      Jesus, when he began his ministry, was about thirty years of
      age, being the son (as was supposed) of Joseph, the son of
      Heli, the son of Matthat, the son of Levi, the son of
      Melchi, the son of Jannai, the son of Joseph, (Luke 3:23-24)
```
I also added a new command, `sword-to-org-insert-passage`, that makes it easy to insert passages directly into the buffer as plain text like this.

What do you think?  :)

**Comment by alphapapa** [comment]
Well, that got a bit messy.  I kept forgetting little things.  Anyway, it's on the master branch now.
