### ISSUE TITLE
Cannot find diatheke - Win10

### ISSUE THREAD

**Issue by Arjay-El** [alphapapa/sword-to-org#6]
Is there a way to hard code a path to diatheke in your code? It cannot find it even though I installed it with Xiphos and also copied it to several directories that are in the path and then created a directory for it with its own path. Its a windows thing of course. Perhaps if it had a stated path like "c:/sword/diatheke.exe", my problem would be solved.
Thanks

**Comment by alphapapa** [comment]
You could adjust the path to the command in the code, but probably a better solution would be to ensure that `diatheke.exe` is in the `PATH` environment variable for the Emacs process you're using.  I'm guessing that you're running Emacs from a shortcut that doesn't have the same `PATH` as the terminal you're working in.

**Comment by Arjay-El** [comment]
Reset and checked all paths and it worked fine. Win10 is sometimes baffling where it looks for things even though you have explicitly called them out. Thanks for the great package,.
